name: 'Stryker evaluator'
description: 'Stryker evaluator action for Tryber projects'
inputs:
  pr_author_username:
    description: 'Pull Request author username'
    required: true
outputs:
  result:
    description: 'Stryker unit tests JSON results in base64 format.'
runs:
  using: 'docker'
  image: 'Dockerfile'
